apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-restart-notifier-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-restart-notifier-operator-role
subjects:
- kind: ServiceAccount
  name: pod-restart-notifier-operator-sa
  namespace: "{{ .Values.namespace }}"
